---
driver:
  name: vagrant
  customize:
    memory: 2560

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.8.1 # to match my chef environment version, alter as-needed
  chef_omnibus_install_options: -d /tmp/vagrant-cache/vagrant_omnibus

platforms:
  - name: ubuntu-14.04
    driver:
      box: ubuntu/trusty64

suites:
- name: default
  run_list:
    - apt
    - java
    - recipe[ele-repose::default]
    - recipe[ele-repose::filter-keystone-v2]
    - recipe[ele-repose::filter-extract-device-id]
    - recipe[ele-repose::filter-valkyrie-authorization]
    - recipe[repose::filter-slf4j-http-logging]
    - recipe[repose::filter-header-normalization]
    - recipe[repose::filter-header-translation]
    - recipe[repose::service-http-connection-pool]
    - recipe[repose::service-dist-datastore]
  attributes:
    repose:
      client_auth:
        auth_provider: 'OPENSTACK'
      rewrite_host_header: false
    ele:
      datacenter: "ord1"
      us_identity_service_url_2: "https://staging.identity.api.rackspacecloud.com./v2.0"
      us_auth_service_username: "us-admin"
- name: stage_lon3_keystone
  run_list:
    - apt
    - java
    - recipe[ele-repose::default]
    - recipe[ele-repose::filter-keystone-v2]
  provisioner:
    client_rb:
      environment: stage
  attributes:
    repose:
      client_auth:
        auth_provider: 'OPENSTACK'
      rewrite_host_header: false
    networks:
      ipaddress_eth0: 127.0.0.1
    ele:
      datacenter: "lon3"
      uk_identity_service_url_2: "https://lon.staging.identity.api.rackspacecloud.com./v2.0"
      uk_auth_service_username: "uk-admin"
  data_bags_path: "test/integration/data_bags"
  environments_path: "test/integration/environments"
  encrypted_data_bag_secret_key_path: "test/integration/default/encrypted_data_bag_secret"
- name: stage_dfw1_keystone
  run_list:
    - apt
    - java
    - recipe[ele-repose::default]
    - recipe[ele-repose::filter-keystone-v2]
  provisioner:
    client_rb:
      environment: stage
  attributes:
    repose:
      client_auth:
        auth_provider: 'OPENSTACK'
      rewrite_host_header: false
    networks:
      ipaddress_eth0: 127.0.0.1
    ele:
      datacenter: "dfw1"
      us_identity_service_url_2: "https://staging.identity.api.rackspacecloud.com./v2.0"
      us_auth_service_username: "us-admin"
  data_bags_path: "test/integration/data_bags"
  environments_path: "test/integration/environments"
  encrypted_data_bag_secret_key_path: "test/integration/default/encrypted_data_bag_secret"
