name 'ele-repose'
maintainer 'Rackspace'
maintainer_email 'sfo-devops@lists.rackspace.com'
license 'Apache 2.0'
description 'Installs/Configures ele-repose'
long_description 'Installs/Configures ele-repose'
version '0.3.4'

depends 'apt'
depends 'java'
depends 'repose'
